<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoanProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $loanProducts = [
            [
                'loan_product_name' => 'Easy Personal Loan',
                'loan_enable_parameters' => true,
                'default_loan_released_date' => true,
                'loan_disbursed_by_id' => json_encode([1, 2]), // Cash, Bank Transfer
                'min_loan_principal_amount' => 500,
                'default_loan_principal_amount' => 5000,
                'max_loan_principal_amount' => 50000,
                'loan_interest_method' => 'flat_rate',
                'loan_interest_type' => 'percentage',
                'loan_interest_period' => 'Month',
                'min_loan_interest' => 1.0,
                'default_loan_interest' => 2.5,
                'max_loan_interest' => 5.0,
                'loan_duration_period' => 'Months',
                'min_loan_duration' => 1,
                'default_loan_duration' => 6,
                'max_loan_duration' => 12,
                'loan_payment_scheme_id' => json_encode([1, 2]),
                'min_loan_num_of_repayments' => 1,
                'default_loan_num_of_repayments' => 6,
                'max_loan_num_of_repayments' => 12,
                'loan_decimal_places' => 'round_off_to_two_decimal',
                'loan_decimal_places_adjust_each_interest' => false,
                'repayment_order' => json_encode(['principal', 'interest', 'fees']),
                'automatic_payments' => true,
                'payment_posting_period' => 1,
                'after_maturity_extend_loan' => false,
                'after_maturity_percentage_or_fixed' => 'percentage',
                'after_maturity_calculate_interest_on' => null,
                'after_maturity_loan_interest' => null,
                'after_maturity_recurring_period_num' => null,
                'after_maturity_recurring_period_payment_scheme_id' => null,
                'after_maturity_num_of_repayments' => null,
                'after_maturity_include_fees' => false,
                'after_maturity_past_maturity_status' => false,
                'first_repayment_amount' => null,
                'last_repayment_amount' => null,
                'override_each_repayment_amount' => null,
                'loan_interest_each_repayment_pro_rata' => false,
                'loan_interest_schedule' => 'charge_interest_normally',
                'loan_principal_schedule' => 'charge_principal_normally',
                'loan_balloon_repayment_amount' => null,
                'loan_move_first_repayment_date_days' => null,
                'loan_schedule_description' => 'Standard personal loan with flexible repayment',
                'stop_loan_duplicate_repayments' => false,
                'loan_status_id' => null,
                'dea_cash_bank_account' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'loan_product_name' => 'Kikundi Group Loan',
                'loan_enable_parameters' => true,
                'default_loan_released_date' => false,
                'loan_disbursed_by_id' => json_encode([1, 2]),
                'min_loan_principal_amount' => 1000,
                'default_loan_principal_amount' => 10000,
                'max_loan_principal_amount' => 200000,
                'loan_interest_method' => 'reducing_rate_equal_installments',
                'loan_interest_type' => 'percentage',
                'loan_interest_period' => 'Month',
                'min_loan_interest' => 1.5,
                'default_loan_interest' => 3.0,
                'max_loan_interest' => 6.0,
                'loan_duration_period' => 'Months',
                'min_loan_duration' => 3,
                'default_loan_duration' => 12,
                'max_loan_duration' => 24,
                'loan_payment_scheme_id' => json_encode([1, 2]),
                'min_loan_num_of_repayments' => 3,
                'default_loan_num_of_repayments' => 12,
                'max_loan_num_of_repayments' => 24,
                'loan_decimal_places' => 'round_off_to_two_decimal',
                'loan_decimal_places_adjust_each_interest' => false,
                'repayment_order' => json_encode(['interest', 'principal', 'fees']),
                'automatic_payments' => false,
                'payment_posting_period' => null,
                'after_maturity_extend_loan' => true,
                'after_maturity_percentage_or_fixed' => 'percentage',
                'after_maturity_calculate_interest_on' => 1,
                'after_maturity_loan_interest' => 3.5,
                'after_maturity_recurring_period_num' => 1,
                'after_maturity_recurring_period_payment_scheme_id' => 1,
                'after_maturity_num_of_repayments' => 6,
                'after_maturity_include_fees' => true,
                'after_maturity_past_maturity_status' => false,
                'first_repayment_amount' => null,
                'last_repayment_amount' => null,
                'override_each_repayment_amount' => null,
                'loan_interest_each_repayment_pro_rata' => true,
                'loan_interest_schedule' => 'charge_interest_normally',
                'loan_principal_schedule' => 'charge_principal_normally',
                'loan_balloon_repayment_amount' => null,
                'loan_move_first_repayment_date_days' => 2,
                'loan_schedule_description' => 'Loan designed for small business groups',
                'stop_loan_duplicate_repayments' => false,
                'loan_status_id' => null,
                'dea_cash_bank_account' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'loan_product_name' => 'Imarisha Biashara Loan',
                'loan_enable_parameters' => true,
                'default_loan_released_date' => false,
                'loan_disbursed_by_id' => json_encode([2]), // Bank transfer only
                'min_loan_principal_amount' => 5000,
                'default_loan_principal_amount' => 50000,
                'max_loan_principal_amount' => 500000,
                'loan_interest_method' => 'compound_interest',
                'loan_interest_type' => 'percentage',
                'loan_interest_period' => 'Month',
                'min_loan_interest' => 2.0,
                'default_loan_interest' => 4.0,
                'max_loan_interest' => 8.0,
                'loan_duration_period' => 'Months',
                'min_loan_duration' => 6,
                'default_loan_duration' => 12,
                'max_loan_duration' => 36,
                'loan_payment_scheme_id' => json_encode([1]),
                'min_loan_num_of_repayments' => 6,
                'default_loan_num_of_repayments' => 12,
                'max_loan_num_of_repayments' => 36,
                'loan_decimal_places' => 'round_off_to_two_decimal',
                'loan_decimal_places_adjust_each_interest' => false,
                'repayment_order' => json_encode(['principal', 'interest']),
                'automatic_payments' => true,
                'payment_posting_period' => 1,
                'after_maturity_extend_loan' => false,
                'after_maturity_percentage_or_fixed' => 'percentage',
                'after_maturity_calculate_interest_on' => null,
                'after_maturity_loan_interest' => null,
                'after_maturity_recurring_period_num' => null,
                'after_maturity_recurring_period_payment_scheme_id' => null,
                'after_maturity_num_of_repayments' => null,
                'after_maturity_include_fees' => false,
                'after_maturity_past_maturity_status' => false,
                'first_repayment_amount' => null,
                'last_repayment_amount' => null,
                'override_each_repayment_amount' => null,
                'loan_interest_each_repayment_pro_rata' => false,
                'loan_interest_schedule' => 'charge_interest_normally',
                'loan_principal_schedule' => 'charge_principal_normally',
                'loan_balloon_repayment_amount' => null,
                'loan_move_first_repayment_date_days' => null,
                'loan_schedule_description' => 'Financing for vehicles, machinery, or equipment',
                'stop_loan_duplicate_repayments' => false,
                'loan_status_id' => null,
                'dea_cash_bank_account' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('loan_products')->insert($loanProducts);
    }
}
