<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Collection Sheet #{{ $collectionSheet->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .summary-box { background: #f8f9fa; padding: 15px; margin: 10px 0; border: 1px solid #dee2e6; }
        .table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f2f2f2; }
        .badge { padding: 3px 8px; border-radius: 3px; font-size: 10px; }
        .badge-success { background: #d4edda; color: #155724; }
        .badge-warning { background: #fff3cd; color: #856404; }
        .badge-danger { background: #f8d7da; color: #721c24; }
        .badge-secondary { background: #e2e3e5; color: #383d41; }
        .text-right { text-align: right; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Collection Sheet #{{ $collectionSheet->id }}</h1>
        <p>
            <strong>Date:</strong> {{ $collectionSheet->collection_date->format('F d, Y') }} | 
            <strong>Branch:</strong> {{ $collectionSheet->branch->name }} | 
            <strong>Staff:</strong> {{ $collectionSheet->staff->full_name }}
        </p>
    </div>

    <div class="summary-box">
        <h3>Collection Summary</h3>
        <table width="100%">
            <tr>
                <td width="25%"><strong>Total Expected:</strong> {{ number_format($collectionSheet->total_expected, 2) }}</td>
                <td width="25%"><strong>Total Collected:</strong> {{ number_format($collectionSheet->total_collected, 2) }}</td>
                <td width="25%"><strong>Sheet Type:</strong> {{ ucfirst($collectionSheet->sheet_type) }}</td>
                <td width="25%"><strong>Status:</strong> {{ ucfirst($collectionSheet->status) }}</td>
            </tr>
        </table>
    </div>

    <h3>Collection Items</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Borrower</th>
                <th>Loan ID</th>
                <th>Expected Amount</th>
                <th>Collected Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($collectionSheet->items as $item)
                <tr>
                    <td>{{ $item->borrower->full_name }}</td>
                    <td>LOAN-{{ $item->loan_id }}</td>
                    <td>{{ number_format($item->expected_amount, 2) }}</td>
                    <td>{{ number_format($item->collected_amount, 2) }}</td>
                    <td>
                        @php
                            $statusColors = [
                                'pending' => 'secondary',
                                'collected' => 'success',
                                'partial' => 'warning',
                                'missed' => 'danger'
                            ];
                        @endphp
                        <span class="badge badge-{{ $statusColors[$item->collection_status] }}">
                            {{ ucfirst($item->collection_status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2" class="text-right">Totals:</th>
                <th>{{ number_format($collectionSheet->items->sum('expected_amount'), 2) }}</th>
                <th>{{ number_format($collectionSheet->items->sum('collected_amount'), 2) }}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>

    @if($collectionSheet->notes)
        <div class="notes">
            <h3>Notes</h3>
            <p>{{ $collectionSheet->notes }}</p>
        </div>
    @endif

    <div class="footer">
        <p>Generated on: {{ now()->format('F d, Y \a\t h:i A') }} | 
           Generated by: {{ auth()->user()->name ?? 'System' }}</p>
    </div>
</body>
</html>